### PR TITLE
Create a separate attribute to indicate whether the node is a master.

### PR DESCRIPTION
**Pull request by brenttheisen**

### CODE REVIEW

**Comment by Pepelo** [comment]
So when would `is_master` be `true`? when one passes it as an arg in the `knife` command?

**Comment by brenttheisen** [comment]
@Pepelo: It should be set in the `nodes/node.json` for whatever node is going to be your Spark master. For our Womply stuff see [this diff](https://github.com/OtoAnalytics/womply-kitchen/compare/spark_chef_fail_fix).

**Comment by Pepelo** [comment]
Gotcha... looks good then.

**Comment by Pepelo** [comment]
... and I don't seem to have the right to merge... hmmm... :-/

**Comment by brenttheisen** [comment]
@Pepelo: Yeah, this is a public repo of mine. Nothing specific to Womply here. I'll merge when/if I get a :+1: from @msilvey.

**Comment by Pepelo** [comment]
Gotcha... didn't realize that until now... lol

**Comment by msilvey** [comment]
looks good. i have a pile of wants related to how a chef recipe rolls this stuff out but they are all beyond scope for now. :)

**Pull request merged**
